### ISSUE TITLE
Compatibility with redmine 5.0

### ISSUE THREAD

**Issue by luethralf** [fredsdc/redmine_web_forms#3]
Is this plugin compatible with redmine 5.0?

**Comment by fredsdc** [comment]
Probably, I don't know. I'm planning to migrate everything here to Redmine 5 by the end of the year, but I don't know if Redmine had any drastic changes since version 4. Please report if you have any issues.

**Comment by cicerocampagnuci** [comment]
I´m using redmine bitnami 5. The instalation of this plugin have no erros, but, in order to execute, clicking the button New WebForm, i receive the error:

**"Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

[Back]"**

And the log shows this:

**"F, [2022-09-12T20:43:58.824046 #7368] FATAL -- : [6882f61e-3a9a-4494-85c8-4daabb3fece7]   
[6882f61e-3a9a-4494-85c8-4daabb3fece7] ActionView::Template::Error (undefined method `allow_attachments' for #<Webform:0x000002171f60ea40>):"**

Can you help me ?
Thanks in advance.
Cicero

**Comment by fredsdc** [comment]
Hi, thanks for reporting. I think it is.
It was missing a migration file, sorry.
Please git pull again, migrate to current version and try again.
