### ISSUE TITLE
no workflow to create issue user roles canot add issues

### ISSUE THREAD

**Issue by etlownoise** [fredsdc/redmine_web_forms#6]
How can this error be addressed? There is no much documentation about it. Still is a great plugin based on the description you have provided.

**Comment by fredsdc** [comment]
It means a user with the given role wouldn't be able to create the issue, because he doesn't have the workflow from a "new issue" to the issue's initial state. I don't know if Redmine enforces it now, but it may in the future, in any case I decided to enforce it in the plugin.

Go to Workflows, chose the same role/tracker you used in your webform, edit, make a link from "new issue" to the state you chose in your webform, save.

**Comment by fredsdc** [comment]
By the way, if you can come up with a better error message, please post it.
